import jsPDF from 'jspdf';

/**
 * Parse markdown report string into structured sections.
 */
function parseReport(markdown: string) {
  const lines = markdown.split('\n');
  const title = lines.find(l => l.startsWith('# '))?.replace(/^#\s+/, '').replace(/[🎯📋💰⭐🗺️💡⚠️🔗]/g, '').trim() || 'PARAM Report';

  // Extract executive summary (text between first heading and second heading)
  let executiveSummary = '';
  const sections: { heading: string; content: string }[] = [];
  let currentHeading = '';
  let currentContent: string[] = [];

  for (const line of lines) {
    if (line.startsWith('## ') || line.startsWith('# ')) {
      if (currentHeading) {
        const content = currentContent.join('\n').trim();
        if (currentHeading.toLowerCase().includes('summary') || currentHeading.toLowerCase().includes('executive')) {
          executiveSummary = content;
        } else {
          sections.push({ heading: currentHeading, content });
        }
      }
      currentHeading = line.replace(/^#{1,3}\s+/, '').replace(/[🎯📋💰⭐🗺️💡⚠️🔗✅📍🏨🍽️🎒🚆✈️🏖️📝🔑📊🎉🌟🔄💭🧠🎨📱💻🌐📌🔍📈]/g, '').trim();
      currentContent = [];
    } else {
      currentContent.push(line);
    }
  }
  if (currentHeading) {
    const content = currentContent.join('\n').trim();
    if (currentHeading.toLowerCase().includes('summary') || currentHeading.toLowerCase().includes('executive')) {
      executiveSummary = content;
    } else {
      sections.push({ heading: currentHeading, content });
    }
  }

  return { title, executiveSummary, sections };
}

function cleanText(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`(.*?)`/g, '$1')
    .replace(/\[(.*?)\]\(.*?\)/g, '$1')
    .replace(/[🎯📋💰⭐🗺️💡⚠️🔗✅📍🏨🍽️🎒🚆✈️🏖️📝🔑📊🎉🌟🔄💭🧠🎨📱💻🌐📌🔍📈]/g, '')
    .trim();
}

export async function exportReportAsPDF(markdownReport: string): Promise<string> {
  const { title, executiveSummary, sections } = parseReport(markdownReport);

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = 20;

  const addText = (text: string, fontSize: number, fontStyle: string, color: [number, number, number], maxWidth?: number) => {
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', fontStyle);
    pdf.setTextColor(...color);
    const cleaned = cleanText(text);
    const lines = pdf.splitTextToSize(cleaned, maxWidth || contentWidth);
    for (const line of lines) {
      if (yPos > 270) { pdf.addPage(); yPos = 20; }
      pdf.text(line, margin, yPos);
      yPos += fontSize * 0.5;
    }
    yPos += 3;
  };

  // Header bar
  pdf.setFillColor(124, 106, 247);
  pdf.rect(0, 0, 210, 18, 'F');
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(255, 255, 255);
  pdf.text('PARAM — AUTONOMOUS AI AGENT', margin, 12);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text(new Date().toLocaleString(), 210 - margin, 12, { align: 'right' });

  yPos = 30;

  // Title
  addText(title, 18, 'bold', [15, 15, 20]);
  yPos += 2;

  // Stats bar
  pdf.setFillColor(245, 245, 250);
  pdf.rect(margin, yPos, contentWidth, 10, 'F');
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 120);
  pdf.text(`Generated by PARAM Multi-Agent System  |  ${new Date().toLocaleDateString()}`, margin + 3, yPos + 6);
  yPos += 16;

  // Executive Summary
  if (executiveSummary) {
    pdf.setFillColor(237, 233, 254);
    pdf.rect(margin, yPos, contentWidth, 6, 'F');
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(83, 74, 183);
    pdf.text('EXECUTIVE SUMMARY', margin + 3, yPos + 4);
    yPos += 10;
    addText(executiveSummary, 9.5, 'normal', [50, 50, 70]);
    yPos += 4;
  }

  // Sections
  for (const section of sections) {
    if (yPos > 250) { pdf.addPage(); yPos = 20; }

    pdf.setDrawColor(124, 106, 247);
    pdf.setLineWidth(0.5);
    pdf.line(margin, yPos, margin + contentWidth, yPos);
    yPos += 5;

    addText(section.heading, 11, 'bold', [60, 50, 120]);

    // Parse content into lines/bullets
    const contentLines = section.content.split('\n').filter(l => l.trim());
    for (const line of contentLines) {
      if (yPos > 270) { pdf.addPage(); yPos = 20; }

      const trimmed = line.trim();
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ') || trimmed.match(/^\d+\.\s/)) {
        const bullet = trimmed.replace(/^[-*]\s+/, '').replace(/^\d+\.\s+/, '');
        pdf.setFillColor(124, 106, 247);
        pdf.circle(margin + 2, yPos - 1, 1, 'F');
        addText(bullet, 9, 'normal', [40, 40, 60]);
      } else if (trimmed.startsWith('|')) {
        // Skip table formatting, add as text
        addText(trimmed.replace(/\|/g, '  '), 8, 'normal', [60, 60, 80]);
      } else if (trimmed.startsWith('###')) {
        addText(trimmed.replace(/^###\s+/, ''), 10, 'bold', [50, 40, 100]);
      } else {
        addText(trimmed, 9.5, 'normal', [50, 50, 70]);
      }
    }
    yPos += 4;
  }

  // Footer on every page
  const totalPages = (pdf as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(7);
    pdf.setTextColor(150, 150, 170);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Generated by PARAM Autonomous Multi-Agent System', margin, 290);
    pdf.text(`Page ${i} of ${totalPages}`, 210 - margin, 290, { align: 'right' });
  }

  const filename = `PARAM_${title.replace(/\s+/g, '_').slice(0, 40)}_${Date.now()}.pdf`;
  pdf.save(filename);
  return filename;
}
